label: basicmessage_storage

# Admin
admin: [ 0.0.0.0, 3001 ]
admin-insecure-mode: true
jwt-secret: insecure-jwt-secret

# Transport
inbound-transport:
  - [ http, 0.0.0.0, 3000 ]
  - [ ws, 0.0.0.0, 3002 ]
outbound-transport: http
endpoint:
  - http://host.docker.internal:3000

# plugins
plugin:
  - basicmessage_storage.v1_0

#config
genesis-url: http://test.bcovrin.vonx.io/genesis

# Multi-tenancy
multitenant: true
multitenant-admin: true
multitenancy-config: '{"wallet-type":"askar-profile","wallet-name":"askar-wallet"}'

# Wallet
wallet-type: askar
log-level: info
auto-provision: true

auto-accept-invites: true
auto-respond-messages: true
